version: "3"

services:
  mqtt-broker-fact1:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_fact1
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - network_mqtt_fact1
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  influxdb-fact1:
    image: influxdb
    container_name: influxdb_fact1
    restart: always
    ports:
      - "8086:8086"
    networks:
      - network_mqtt_fact1
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password1234
      - DOCKER_INFLUXDB_INIT_ORG=fact1_org
      - DOCKER_INFLUXDB_INIT_BUCKET=fact1_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=4eYvsu8wZCJ6tKuE2sxvFHkvYFwSMVK0011hEEiojvejzpSaij86vYQomN_12au6eK-2MZ6Knr-Sax201y70w==fact1
  
  telegraf-fact1:
    image: telegraf
    container_name: telegraf_fact1
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mqtt-broker-fact1
      - influxdb-fact1
    networks:
      - network_mqtt_fact1
  
  grafana-fact1:
    image: grafana/grafana
    container_name: grafana_fact1
    restart: always
    ports:
      - "3000:3000"
    networks:
      - network_mqtt_fact1
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb-fact1

networks:
  network_mqtt_fact1:

volumes:
  grafana-data:
  influxdb-data:
  influxdb-config: